### PR TITLE
Split help and pl output accross multiple calls to cli.do()

### LINKED ISSUE #258: Fail on Big Bandit with CLI + Help Command
On current Main branch when using the CLI on Big Bandit, executing the help command causes the Tx to fail with rapid LED flash and become unresponsive.

### PR DESCRIPTION
**Pull request by brad112358**
Fixes #258

### CODE REVIEW

**Comment by jlpoltrack** [comment]
Quick test on Big Bandit - pl command no longer causes fail state.

**Comment by olliw42** [comment]
nice, so you suggest to follow the idea to output in smaller chunks
like that
on first look my first impulse is that the two fields for managing the output, output_pending and output_index, may go into one, by adding "substructure" to the enum. There thus would e.g. be two entries for the pl-tx chunck, one which just does it, and one as part of the sequence of pl. It's then more like a simple state machine. I might be wrong but I think worth a look.

File: mLRS/CommonTx/cli.h [hunk 1]
```diff
@@ -290,11 +290,17 @@ class tTxCli
         CLI_STATE_STATS,
     } CLI_STATE_ENUM;
 
+    typedef enum {
+        CLI_OUTPUT_NONE = 0,
+        CLI_OUTPUT_HELP,
+        CLI_OUTPUT_PL,
+    } CLI_OUTPUT_ENUM;
```
Comment (olliw42) [inline mLRS/CommonTx/cli.h:297]: may be PRINT instead of OUTPUT, as the functions which it manages are also called print

File: mLRS/CommonTx/cli.h [hunk 2]
```diff
@@ -334,6 +340,10 @@ class tTxCli
     uint8_t task_pending;
     int32_t task_value;
 
+    CLI_OUTPUT_ENUM output_pending;
```
Comment (olliw42) [inline mLRS/CommonTx/cli.h:343]: maybe PRINT/print instead of OUTPUT/output

File: mLRS/CommonTx/cli.h [hunk 3]
```diff
@@ -334,6 +340,10 @@ class tTxCli
...
+    int16_t output_index;
```
Comment (olliw42) [inline mLRS/CommonTx/cli.h:344]: maybe print_chunk_idx, more descriptie IMHO and not so easily confused with the param idx, it's also a bit more along what we use in mavlink

File: mLRS/CommonTx/cli.h [hunk 4]
```diff
@@ -334,6 +340,10 @@ class tTxCli
...
+    int8_t output_flag;
```
Comment (olliw42) [inline mLRS/CommonTx/cli.h:345]: maybe print_pl_flag (as it's only for pl AFAICS)

File: mLRS/CommonTx/cli.h [hunk 5]
```diff
@@ -351,6 +361,10 @@ void tTxCli::Init(tSerialBase* const _comport)
     task_pending = TX_TASK_NONE;
     task_value = 0;
 
+    output_pending = CLI_OUTPUT_NONE;
+    output_index = 0;
+    output_flag = 0;
```
Comment (olliw42) [inline mLRS/CommonTx/cli.h:366]: while a long due leftover, I think we could use the opportunity to also add an enum for the flags ... was ugly to read so far

File: mLRS/CommonTx/cli.h [hunk 6]
```diff
@@ -543,22 +557,29 @@ void tTxCli::print_param(uint8_t idx)
...
+    output_pending = CLI_OUTPUT_PL;
+    if (output_index == 0 && (output_flag == 0 || output_flag == 1 || output_flag == 3) && !connected()) {
         putsn("warn: receiver not connected");
     }
 
-    for (uint8_t idx = 0; idx < SETUP_PARAMETER_NUM; idx++) {
-        if ((flag == 1) && (setup_param_is_tx(idx) || setup_param_is_rx(idx))) continue;
-        if ((flag == 2) && !setup_param_is_tx(idx)) continue;
-        if ((flag == 3) && !setup_param_is_rx(idx)) continue;
+    for (uint8_t count = 0; output_index < SETUP_PARAMETER_NUM; output_index++) {
```
Comment (olliw42) [inline mLRS/CommonTx/cli.h:567]: no, pl don't do this kind of K&R style C weiredness, either a clear plain for or a clear plain while

File: mLRS/CommonTx/cli.h [hunk 7]
```diff
@@ -543,22 +557,29 @@ void tTxCli::print_param(uint8_t idx)
...
+        if ((output_flag == 3) && !setup_param_is_rx(output_index)) continue;
 
-        if ((flag == 0 || flag == 3) && !connected() && setup_param_is_rx(idx)) continue;
+        if ((output_flag == 0 || output_flag == 3) && !connected() && setup_param_is_rx(output_index)) continue;
 
-        print_param(idx);
-        //delay_ms(10);
+        print_param(output_index);
+        count++;
+        if (count > 1) {
```
Comment (olliw42) [inline mLRS/CommonTx/cli.h:576]: see previous comment

File: mLRS/CommonTx/cli.h [hunk 8]
```diff
@@ -639,36 +660,46 @@ char unit[32];
...
+        putsn("  pl          -> list all parameters");
+        putsn("  pl c        -> list common parameters");
+        putsn("  pl tx       -> list Tx parameters");
+        putsn("  pl rx       -> list Rx parameters");
+
+        putsn("  p name          -> get parameter value");
+        putsn("  p name = value  -> set parameter value");
+        putsn("  p name = ?      -> get parameter value and list of allowed values");
+        putsn("  pstore      -> store parameters");
+        output_index++; // Do next chunk next time
```
Comment (olliw42) [inline mLRS/CommonTx/cli.h:677]: this here would be a clear example where one could use just the enum with more subsructure to step through the pieces

File: mLRS/CommonTx/cli.h [hunk 9]
```diff
@@ -683,6 +714,14 @@ bool rx_param_changed;
 
     //puts(".");
 
+    if (output_pending == CLI_OUTPUT_HELP) {
```
Comment (olliw42) [inline mLRS/CommonTx/cli.h:717]: maybe a switch

File: mLRS/CommonTx/cli.h [hunk 10]
```diff
@@ -710,10 +749,10 @@ bool rx_param_changed;
         if (is_cmd("help"))  { print_help(); } else
         if (is_cmd("?"))     { print_help(); } else
         if (is_cmd("v"))     { print_device_version(); } else
-        if (is_cmd("pl"))    { print_config_id(); print_param_list(0); } else
-        if (is_cmd("pl c"))  { print_config_id(); print_param_list(1); } else
-        if (is_cmd("pl tx")) { print_config_id(); print_param_list(2); } else
-        if (is_cmd("pl rx")) { print_config_id(); print_param_list(3);
+        if (is_cmd("pl"))    { print_config_id(); output_flag = 0; print_param_list(); } else
```
Comment (olliw42) [inline mLRS/CommonTx/cli.h:752]: that's a bit weired from a logic point of view, as the output state machine is setup in mixed places, not so nice architecture wise. I guess I would separate into two functions, one to start the print and one to handle the prints. If one keeps on with the multiple fields
if all fields can be condensed into on enum, one would need just one handler, and could set the task here

for the print_help() we have the same logocal issue that the same function needs to do both start/trigger and handling. There it's even weirder as the output_index is used to start the state machine.

I'm not sure form scratch what the nicest solution would be but I think we could spend few efforts on making this look nice

**Comment by olliw42** [comment]
if I'm understanding correctly, the pl is chunked into the sections c, tx, rx. I'm not sure I totally understand the timing aspect here. cli.Do() is done only in the while start part, that is each start of transmission. What would happen with FLRC? How would it interfere with the delay thing? I would think that with proper chunking and timing the delay stuff should go, i.e., any proper timing should be done now in the print-chunk handler. 

Has this been tested on anything else than the bandit?

**Comment by jlpoltrack** [comment]
> Has this been tested on anything else than the bandit?

Tests on BetaFPV with pl command with receiver connected:

- FLRC: link drops temporarily
- 50 Hz: lq drop on Tx side (~80%)
- 31 Hz: lq drop on Tx side (~70%)
- 19 Hz: no observed LQ drop

**Comment by brad112358** [comment]
> nice, so you suggest to follow the idea to output in smaller chunks like that on first look my first impulse is that the two fields for managing the output, output_pending and output_index, may go into one, by adding "substructure" to the enum. There thus would e.g. be two entries for the pl-tx chunck, one which just does it, and one as part of the sequence of pl. It's then more like a simple state machine. I might be wrong but I think worth a look.

I don't think so.  You may have missed that this would require about 24 additional states because we are only doing 2 lines of pl output on every call to do().  This is because even help which was only taking 2 or 3 ms can cause a problem so I wanted to keep each call under 2ms.

File: mLRS/CommonTx/cli.h (hunk 3 above)
Comment (brad112358) [reply mLRS/CommonTx/cli.h:344]: In the case of help, it is indeed a chunk index, but in the case of pl, it actually is a parameter index!  In both cases, it's part of our print state and if we are short of RAM, I'd rather not use more of it.  I think I'll call it print index.

**Comment by brad112358** [comment]
> Tests on BetaFPV with pl command with receiver connected:

Thanks for testing!

File: mLRS/CommonTx/cli.h (hunk 6 above)
Comment (brad112358) [reply mLRS/CommonTx/cli.h:567]: OK.  Sometimes I think your code is weird too. :)

File: mLRS/CommonTx/cli.h (hunk 9 above)
Comment (brad112358) [reply mLRS/CommonTx/cli.h:717]: Yes, maybe; especially if we had more states.

**Comment by brad112358** [comment]
> I would think that with proper chunking and timing the delay stuff should go, i.e., any proper timing should be done now in the print-chunk handler.

That's an interesting question.  Currently, the put_cnt flow control hack is completely independent of this PR which seeks only to restrict the main loop delay.  But, I suppose we could break help up into many more pieces and eliminate put_cnt.

I also just realized I forgot to test listfreqs and it is currently causing a crash so we need the same tricks there.

**Comment by jlpoltrack** [comment]
> I'm not worried about the link when we use the CLI, but without this PR, was the LQ drop worse?  Yes, LQ drop is worse on Main.

Tests on BetaFPV with pl command with receiver connected:

- FLRC: 
    - This branch: link drops temporarily
    - Main: link drops temporarily
 - 50 Hz: 
     - This branch: lq drop on Tx side (~80%)
     - Main: link drops temporarily
 - 31 Hz:
    - This branch: lq drop on Tx side (~70%)
    - Main: lq drop on Tx side (~80%)
 - 19 Hz: 
     - This branch: no observed LQ drop
     - Main: lq drop on Tx side (~70%)

Still curious why the fail state seems to only occur with SX127x, perhaps there is better state handling with SX128x.

File: mLRS/CommonTx/cli.h (hunk 10 above)
Comment (brad112358) [reply mLRS/CommonTx/cli.h]: Is the latest commit better?  It now follows the pattern you had established with CLI_STATE_STATS

**Comment by brad112358** [comment]
> I would think that with proper chunking and timing the delay stuff should go, i.e., any proper timing should be done now in the print-chunk handler.

I did end up subsuming the put delay hacks into the print chunk code and I tested it with TXBUFSIZE 0 (128 bytes).  cli.Do() takes under 500 uS now in my tests.

File: mLRS/CommonTx/cli.h (hunk 5 above)
Comment (brad112358) [reply mLRS/CommonTx/cli.h]: Since this is unrelated and you didn't mention what you would want to call the enums, I think I'll pass on this and let you fix it later as you see fit, lest this require another round of changes due to my likely poorly chosen names.

**Comment by brad112358** [comment]
> Still curious why the fail state seems to only occur with SX127x, perhaps there is better state handling with SX128x.

I suspect it's the same reason we saw crashes only with the SX127x when we had the jitter issue.

I suspect my latest revision my have further improved the LQ drops, but I haven't tested anything but 19 Hz.

**Comment by brad112358** [comment]
I fixed a rather significant typo in my comment two up.  The time for Cli.Do() is way down, measuring at less than 50 uS in my tests.  Is there anything holding up merging this now?
